# Build do app em React
FROM node:18-alpine AS build
 
WORKDIR /app
 
COPY package*.json ./
 
RUN npm ci
 
COPY . .

ENV REACT_APP_BACKEND_URL="/api"

RUN npm run build

# Serve o app com Nginx
FROM nginx:stable-alpine AS production

COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf

EXPOSE 80/tcp

CMD ["nginx", "-g", "daemon off;"]