apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: caiquecamargo/pucminas-backend:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "500m"
          requests:
            cpu: "250m"
        envFrom:
        - configMapRef:
            name: backend-configmap
        env:
        - name: FLASK_DB_USER
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: POSTGRES_USER
        - name: FLASK_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: POSTGRES_DB
        - name: FLASK_DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-configmap
              key: POSTGRES_PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50